version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db # Persistent data storage
    networks:
      - mongo-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Pre-installs the Infinity data source plugin
      GF_PLUGINS_PREINSTALL_SYNC: yesoreyeram-infinity-datasource
      GF_SECURITY_ALLOW_EMBEDDING: true
      GF_SESSION_COOKIE_SAMESITE: none

      GF_AUTH_ANONYMOUS_ENABLED: true
      # # GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      # GF_SECURITY_ALLOW_EMBEDDING: true
      # # Required if embedding across different domains with HTTPS
      GF_SECURITY_COOKIE_SAMESITE: none
      GF_SECURITY_COOKIE_SECURE: true
      GF_INSTALL_PLUGINS: vaduga-mapgl-panel@1.6.1

    volumes:
      - ./provisioning/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/grafana/dashboards:/etc/grafana/provisioning/dashboards
      # Dashboard JSONs
      - ./provisioning/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana # Persistent Grafana data
    networks:
      - mongo-network

volumes:
  mongo_data:
    driver: local
  grafana_data:
    driver: local

networks:
  mongo-network:
    driver: bridge